Adding alternative drugs to the DataFrame
The alternative drugs are approved drugs that have the same target

References:
How to select rows from a dataframe based on column values ? - GeeksforGeeks
https://www.geeksforgeeks.org/how-to-select-rows-from-a-dataframe-based-on-column-values/

How to fill missing value based on other columns in Pandas dataframe? - Data Science Stack Exchange
https://datascience.stackexchange.com/questions/17769/how-to-fill-missing-value-based-on-other-columns-in-pandas-dataframe

python - Pandas assign value to cell based on values of other cells in row - Stack Overflow
https://stackoverflow.com/questions/34835906/pandas-assign-value-to-cell-based-on-values-of-other-cells-in-row

Pandas Iterate Over Rows with Examples - Spark By {Examples}
https://sparkbyexamples.com/pandas/iterate-over-rows-in-pandas-dataframe/

Get Unique values in Pandas DataFrame Column | FavTutor
https://favtutor.com/blogs/pandas-unique-values-in-column

python - print the unique values in every column in a pandas dataframe - Stack Overflow
https://stackoverflow.com/questions/27241253/print-the-unique-values-in-every-column-in-a-pandas-dataframe

Pandas Tutorial - describe(), head(), unique() and count() - MLK - Machine Learning Knowledge
https://machinelearningknowledge.ai/pandas-tutorial-describe-head-unique-and-count/

Pandas: How to Find Unique Values in a Column - Statology
https://www.statology.org/pandas-unique-values-in-column/

6 Ways to Convert List to String in Python? | Simplilearn
https://www.simplilearn.com/tutorials/python-tutorial/list-to-string-in-python

python - Why does passing a tuple cause a key error in pandas? - Stack Overflow
https://stackoverflow.com/questions/37953707/why-does-passing-a-tuple-cause-a-key-error-in-pandas

ValueError: The truth value of a series is ambiguous. use a.empty, a.bool(), a.item(), a.any() or a.all() – LearnDataSci
https://www.learndatasci.com/solutions/python-valueerror-truth-value-series-ambiguous-use-empty-bool-item-any-or-all/

Pandas: How to Check if Column Contains String - Statology
https://www.statology.org/pandas-check-if-column-contains-string/

5 ways to apply an IF condition in Pandas DataFrame – Data to Fish
https://datatofish.com/if-condition-in-pandas-dataframe/

KeyError Pandas – How To Fix | Data Independent
https://dataindependent.com/pandas/keyerror-pandas-how-to-fix/

python - Pandas: select cell value using pd.at with condition - Stack Overflow
https://stackoverflow.com/questions/50364049/pandas-select-cell-value-using-pd-at-with-condition

pandas.DataFrame.loc — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

Pandas Add Column Methods: A Guide | Built In
https://builtin.com/data-science/pandas-add-column

pandas.Series.apply — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html#pandas.Series.apply

pandas.DataFrame.query — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html

Pandas.DataFrame.query() by Examples - Spark By {Examples}
https://sparkbyexamples.com/pandas/pandas-dataframe-query-examples/

How to get column names in Pandas dataframe - GeeksforGeeks
https://www.geeksforgeeks.org/how-to-get-column-names-in-pandas-dataframe/

python - Create new column based on values from other columns / apply a function of multiple columns, row-wise in Pandas - Stack Overflow
https://stackoverflow.com/questions/26886653/create-new-column-based-on-values-from-other-columns-apply-a-function-of-multi

A Simple Guide to Inplace Operations in Pandas | by Avi Chawla | Towards Data Science
https://towardsdatascience.com/a-simple-guide-to-inplace-operations-in-pandas-7a1d97ecce24

Why You Should Probably Never Use pandas inplace=True | by Sven Harris | Towards Data Science
https://towardsdatascience.com/why-you-should-probably-never-use-pandas-inplace-true-9f9f211849e4
https://towardsdatascience.com/why-you-should-probably-never-use-pandas-inplace-true-9f9f211849e4#:~:text=Using%20the%20inplace%3DTrue%20keyword,which%20you%20apply%20it%20to.

How do I get a list of all the duplicate items using pandas in python? - Stack Overflow
https://stackoverflow.com/questions/14657241/how-do-i-get-a-list-of-all-the-duplicate-items-using-pandas-in-python

pandas.DataFrame.duplicated — pandas 2.0.0 documentation
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html

pandas.DataFrame.isin — pandas 2.0.0 documentation
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html

pandas.Series.transform — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.Series.transform.html

pandas.Series.map — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html

pandas.Series.rolling — pandas 2.0.0 documentation
https://pandas.pydata.org/docs/reference/api/pandas.Series.rolling.html

pandas.DataFrame.rolling — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html

[Code]-Rolling windows excluding current rows-pandas
https://www.appsloveworld.com/pandas/100/47/rolling-windows-excluding-current-rows

pandas.Series.where — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.Series.where.html

DataFrame — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/frame.html

pandas.DataFrame.iterrows — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html

pandas.DataFrame.itertuples — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples

pandas.DataFrame.applymap — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html

pandas.DataFrame.all — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html

pandas.DataFrame.filter — pandas 2.0.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.filter.html